# ~/.config/alacritty/alacritty.toml

[general]
import = [
 "~/.config/alacritty/themes/catppuccin_mocha.toml"
]

[env]
WINIT_X11_SCALE_FACTOR = "1.0"
TERM = "xterm-256color"
LANG = "en_US.UTF-8"

[window]
dimensions = { columns = 96, lines = 32 }
padding = { x = 8, y = 8 }
dynamic_padding = true
decorations = "None" # or "Full" for window decorations
opacity = 0.88
blur = true

[font]
normal = { family = "JetbrainsMono Nerd Font", style = "Regular" }
size = 13.75

[colors]
draw_bold_text_with_bright_colors = true

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Beam", blinking = "Off" }
# blink_interval = 500
# blink_timeout = 3

[mouse]
hide_when_typing = true

