linux_display_backend 		wayland
background_opacity          0.75
background_blur             1
cursor_trail                1
window_padding_width        8
font_family                 MesloLGS Nerd Font Mono
font_size                   13.75
hide_window_decorations     yes

# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME
